//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventStar.ClientesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.inventstar.cdejava.lp2/", ConfigurationName="ClientesWS.ClientesWS")]
    public interface ClientesWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasClientesPorNombre_Ap" +
            "ellido_DNIRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasClientesPorNombre_Ap" +
            "ellido_DNIResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIResponse listarTodasClientesPorNombre_Apellido_DNI(InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasClientesPorNombre_Ap" +
            "ellido_DNIRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasClientesPorNombre_Ap" +
            "ellido_DNIResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIResponse> listarTodasClientesPorNombre_Apellido_DNIAsync(InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/modificarPromocionRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/modificarPromocionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.modificarPromocionResponse modificarPromocion(InventStar.ClientesWS.modificarPromocionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/modificarPromocionRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/modificarPromocionResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.modificarPromocionResponse> modificarPromocionAsync(InventStar.ClientesWS.modificarPromocionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/insertarPromocionRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/insertarPromocionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.insertarPromocionResponse insertarPromocion(InventStar.ClientesWS.insertarPromocionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/insertarPromocionRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/insertarPromocionResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.insertarPromocionResponse> insertarPromocionAsync(InventStar.ClientesWS.insertarPromocionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasClientesRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.listarTodasClientesResponse listarTodasClientes(InventStar.ClientesWS.listarTodasClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasClientesRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasClientesResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasClientesResponse> listarTodasClientesAsync(InventStar.ClientesWS.listarTodasClientesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasTarjetasRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasTarjetasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.listarTodasTarjetasResponse listarTodasTarjetas(InventStar.ClientesWS.listarTodasTarjetasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasTarjetasRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasTarjetasResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasTarjetasResponse> listarTodasTarjetasAsync(InventStar.ClientesWS.listarTodasTarjetasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasPromocionesRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasPromocionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.listarTodasPromocionesResponse listarTodasPromociones(InventStar.ClientesWS.listarTodasPromocionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasPromocionesRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/listarTodasPromocionesResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasPromocionesResponse> listarTodasPromocionesAsync(InventStar.ClientesWS.listarTodasPromocionesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarPromocionRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarPromocionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.eliminarPromocionResponse eliminarPromocion(InventStar.ClientesWS.eliminarPromocionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarPromocionRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarPromocionResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarPromocionResponse> eliminarPromocionAsync(InventStar.ClientesWS.eliminarPromocionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.eliminarResponse eliminar(InventStar.ClientesWS.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarResponse> eliminarAsync(InventStar.ClientesWS.eliminarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/insertarClienteRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/insertarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.insertarClienteResponse insertarCliente(InventStar.ClientesWS.insertarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/insertarClienteRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/insertarClienteResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.insertarClienteResponse> insertarClienteAsync(InventStar.ClientesWS.insertarClienteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarTarjetaRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarTarjetaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.eliminarTarjetaResponse eliminarTarjeta(InventStar.ClientesWS.eliminarTarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarTarjetaRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/eliminarTarjetaResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarTarjetaResponse> eliminarTarjetaAsync(InventStar.ClientesWS.eliminarTarjetaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/modificarClienteRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/modificarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.modificarClienteResponse modificarCliente(InventStar.ClientesWS.modificarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/modificarClienteRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/modificarClienteResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.modificarClienteResponse> modificarClienteAsync(InventStar.ClientesWS.modificarClienteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/insertarTarjetaRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/insertarTarjetaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.insertarTarjetaResponse insertarTarjeta(InventStar.ClientesWS.insertarTarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/insertarTarjetaRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/insertarTarjetaResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.insertarTarjetaResponse> insertarTarjetaAsync(InventStar.ClientesWS.insertarTarjetaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/modificarTarjetaRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/modificarTarjetaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InventStar.ClientesWS.modificarTarjetaResponse modificarTarjeta(InventStar.ClientesWS.modificarTarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.inventstar.cdejava.lp2/ClientesWS/modificarTarjetaRequest", ReplyAction="http://services.inventstar.cdejava.lp2/ClientesWS/modificarTarjetaResponse")]
        System.Threading.Tasks.Task<InventStar.ClientesWS.modificarTarjetaResponse> modificarTarjetaAsync(InventStar.ClientesWS.modificarTarjetaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.inventstar.cdejava.lp2/")]
    public partial class cliente : persona {
        
        private bool aceptaPublicidadField;
        
        private bool activoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool aceptaPublicidad {
            get {
                return this.aceptaPublicidadField;
            }
            set {
                this.aceptaPublicidadField = value;
                this.RaisePropertyChanged("aceptaPublicidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.inventstar.cdejava.lp2/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMatField;
        
        private string apellidoPatField;
        
        private string domicilioField;
        
        private string emailField;
        
        private System.DateTime fechaCumpleanhosField;
        
        private bool fechaCumpleanhosFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string numDocumentoField;
        
        private string telefono1Field;
        
        private string telefono2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMat {
            get {
                return this.apellidoMatField;
            }
            set {
                this.apellidoMatField = value;
                this.RaisePropertyChanged("apellidoMat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPat {
            get {
                return this.apellidoPatField;
            }
            set {
                this.apellidoPatField = value;
                this.RaisePropertyChanged("apellidoPat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
                this.RaisePropertyChanged("domicilio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaCumpleanhos {
            get {
                return this.fechaCumpleanhosField;
            }
            set {
                this.fechaCumpleanhosField = value;
                this.RaisePropertyChanged("fechaCumpleanhos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCumpleanhosSpecified {
            get {
                return this.fechaCumpleanhosFieldSpecified;
            }
            set {
                this.fechaCumpleanhosFieldSpecified = value;
                this.RaisePropertyChanged("fechaCumpleanhosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numDocumento {
            get {
                return this.numDocumentoField;
            }
            set {
                this.numDocumentoField = value;
                this.RaisePropertyChanged("numDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono1 {
            get {
                return this.telefono1Field;
            }
            set {
                this.telefono1Field = value;
                this.RaisePropertyChanged("telefono1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string telefono2 {
            get {
                return this.telefono2Field;
            }
            set {
                this.telefono2Field = value;
                this.RaisePropertyChanged("telefono2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.inventstar.cdejava.lp2/")]
    public partial class tarjetaInventstar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private cliente clienteField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private int idTarjetaField;
        
        private int puntosAcumuladosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTarjeta {
            get {
                return this.idTarjetaField;
            }
            set {
                this.idTarjetaField = value;
                this.RaisePropertyChanged("idTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int puntosAcumulados {
            get {
                return this.puntosAcumuladosField;
            }
            set {
                this.puntosAcumuladosField = value;
                this.RaisePropertyChanged("puntosAcumulados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(promocion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(promocionPersonalizada))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.inventstar.cdejava.lp2/")]
    public partial class itemVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idItemVentaField;
        
        private string nombreField;
        
        private double precioUnitarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idItemVenta {
            get {
                return this.idItemVentaField;
            }
            set {
                this.idItemVentaField = value;
                this.RaisePropertyChanged("idItemVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(promocionPersonalizada))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.inventstar.cdejava.lp2/")]
    public partial class promocion : itemVenta {
        
        private bool estadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private tipoDePromocion tipoPromocionField;
        
        private bool tipoPromocionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tipoDePromocion tipoPromocion {
            get {
                return this.tipoPromocionField;
            }
            set {
                this.tipoPromocionField = value;
                this.RaisePropertyChanged("tipoPromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoPromocionSpecified {
            get {
                return this.tipoPromocionFieldSpecified;
            }
            set {
                this.tipoPromocionFieldSpecified = value;
                this.RaisePropertyChanged("tipoPromocionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.inventstar.cdejava.lp2/")]
    public enum tipoDePromocion {
        
        /// <remarks/>
        desayunos,
        
        /// <remarks/>
        antojos_de_la_tarde,
        
        /// <remarks/>
        coffee_for_share,
        
        /// <remarks/>
        otros,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.inventstar.cdejava.lp2/")]
    public partial class promocionPersonalizada : promocion {
        
        private bool activoField;
        
        private string mensajeField;
        
        private tarjetaInventstar tarjetaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tarjetaInventstar tarjeta {
            get {
                return this.tarjetaField;
            }
            set {
                this.tarjetaField = value;
                this.RaisePropertyChanged("tarjeta");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasClientesPorNombre_Apellido_DNI", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class listarTodasClientesPorNombre_Apellido_DNIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public listarTodasClientesPorNombre_Apellido_DNIRequest() {
        }
        
        public listarTodasClientesPorNombre_Apellido_DNIRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasClientesPorNombre_Apellido_DNIResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class listarTodasClientesPorNombre_Apellido_DNIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.cliente[] @return;
        
        public listarTodasClientesPorNombre_Apellido_DNIResponse() {
        }
        
        public listarTodasClientesPorNombre_Apellido_DNIResponse(InventStar.ClientesWS.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPromocion", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class modificarPromocionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.promocionPersonalizada arg0;
        
        public modificarPromocionRequest() {
        }
        
        public modificarPromocionRequest(InventStar.ClientesWS.promocionPersonalizada arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPromocionResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class modificarPromocionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPromocionResponse() {
        }
        
        public modificarPromocionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPromocion", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class insertarPromocionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.promocionPersonalizada arg0;
        
        public insertarPromocionRequest() {
        }
        
        public insertarPromocionRequest(InventStar.ClientesWS.promocionPersonalizada arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPromocionResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class insertarPromocionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPromocionResponse() {
        }
        
        public insertarPromocionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasClientes", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class listarTodasClientesRequest {
        
        public listarTodasClientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasClientesResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class listarTodasClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.cliente[] @return;
        
        public listarTodasClientesResponse() {
        }
        
        public listarTodasClientesResponse(InventStar.ClientesWS.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasTarjetas", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class listarTodasTarjetasRequest {
        
        public listarTodasTarjetasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasTarjetasResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class listarTodasTarjetasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.tarjetaInventstar[] @return;
        
        public listarTodasTarjetasResponse() {
        }
        
        public listarTodasTarjetasResponse(InventStar.ClientesWS.tarjetaInventstar[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasPromociones", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class listarTodasPromocionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public listarTodasPromocionesRequest() {
        }
        
        public listarTodasPromocionesRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasPromocionesResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class listarTodasPromocionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.promocionPersonalizada[] @return;
        
        public listarTodasPromocionesResponse() {
        }
        
        public listarTodasPromocionesResponse(InventStar.ClientesWS.promocionPersonalizada[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPromocion", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class eliminarPromocionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarPromocionRequest() {
        }
        
        public eliminarPromocionRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPromocionResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class eliminarPromocionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPromocionResponse() {
        }
        
        public eliminarPromocionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCliente", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class insertarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.cliente arg0;
        
        public insertarClienteRequest() {
        }
        
        public insertarClienteRequest(InventStar.ClientesWS.cliente arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarClienteResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class insertarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarClienteResponse() {
        }
        
        public insertarClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTarjeta", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class eliminarTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarTarjetaRequest() {
        }
        
        public eliminarTarjetaRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTarjetaResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class eliminarTarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTarjetaResponse() {
        }
        
        public eliminarTarjetaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCliente", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class modificarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.cliente arg0;
        
        public modificarClienteRequest() {
        }
        
        public modificarClienteRequest(InventStar.ClientesWS.cliente arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarClienteResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class modificarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarClienteResponse() {
        }
        
        public modificarClienteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTarjeta", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class insertarTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.tarjetaInventstar arg0;
        
        public insertarTarjetaRequest() {
        }
        
        public insertarTarjetaRequest(InventStar.ClientesWS.tarjetaInventstar arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTarjetaResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class insertarTarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTarjetaResponse() {
        }
        
        public insertarTarjetaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTarjeta", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class modificarTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventStar.ClientesWS.tarjetaInventstar arg0;
        
        public modificarTarjetaRequest() {
        }
        
        public modificarTarjetaRequest(InventStar.ClientesWS.tarjetaInventstar arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTarjetaResponse", WrapperNamespace="http://services.inventstar.cdejava.lp2/", IsWrapped=true)]
    public partial class modificarTarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.inventstar.cdejava.lp2/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTarjetaResponse() {
        }
        
        public modificarTarjetaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesWSChannel : InventStar.ClientesWS.ClientesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesWSClient : System.ServiceModel.ClientBase<InventStar.ClientesWS.ClientesWS>, InventStar.ClientesWS.ClientesWS {
        
        public ClientesWSClient() {
        }
        
        public ClientesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIResponse InventStar.ClientesWS.ClientesWS.listarTodasClientesPorNombre_Apellido_DNI(InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIRequest request) {
            return base.Channel.listarTodasClientesPorNombre_Apellido_DNI(request);
        }
        
        public InventStar.ClientesWS.cliente[] listarTodasClientesPorNombre_Apellido_DNI(string arg0) {
            InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIRequest inValue = new InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).listarTodasClientesPorNombre_Apellido_DNI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIResponse> InventStar.ClientesWS.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIAsync(InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIRequest request) {
            return base.Channel.listarTodasClientesPorNombre_Apellido_DNIAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIResponse> listarTodasClientesPorNombre_Apellido_DNIAsync(string arg0) {
            InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIRequest inValue = new InventStar.ClientesWS.listarTodasClientesPorNombre_Apellido_DNIRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).listarTodasClientesPorNombre_Apellido_DNIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.modificarPromocionResponse InventStar.ClientesWS.ClientesWS.modificarPromocion(InventStar.ClientesWS.modificarPromocionRequest request) {
            return base.Channel.modificarPromocion(request);
        }
        
        public int modificarPromocion(InventStar.ClientesWS.promocionPersonalizada arg0) {
            InventStar.ClientesWS.modificarPromocionRequest inValue = new InventStar.ClientesWS.modificarPromocionRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.modificarPromocionResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).modificarPromocion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.modificarPromocionResponse> InventStar.ClientesWS.ClientesWS.modificarPromocionAsync(InventStar.ClientesWS.modificarPromocionRequest request) {
            return base.Channel.modificarPromocionAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.modificarPromocionResponse> modificarPromocionAsync(InventStar.ClientesWS.promocionPersonalizada arg0) {
            InventStar.ClientesWS.modificarPromocionRequest inValue = new InventStar.ClientesWS.modificarPromocionRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).modificarPromocionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.insertarPromocionResponse InventStar.ClientesWS.ClientesWS.insertarPromocion(InventStar.ClientesWS.insertarPromocionRequest request) {
            return base.Channel.insertarPromocion(request);
        }
        
        public int insertarPromocion(InventStar.ClientesWS.promocionPersonalizada arg0) {
            InventStar.ClientesWS.insertarPromocionRequest inValue = new InventStar.ClientesWS.insertarPromocionRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.insertarPromocionResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).insertarPromocion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.insertarPromocionResponse> InventStar.ClientesWS.ClientesWS.insertarPromocionAsync(InventStar.ClientesWS.insertarPromocionRequest request) {
            return base.Channel.insertarPromocionAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.insertarPromocionResponse> insertarPromocionAsync(InventStar.ClientesWS.promocionPersonalizada arg0) {
            InventStar.ClientesWS.insertarPromocionRequest inValue = new InventStar.ClientesWS.insertarPromocionRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).insertarPromocionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.listarTodasClientesResponse InventStar.ClientesWS.ClientesWS.listarTodasClientes(InventStar.ClientesWS.listarTodasClientesRequest request) {
            return base.Channel.listarTodasClientes(request);
        }
        
        public InventStar.ClientesWS.cliente[] listarTodasClientes() {
            InventStar.ClientesWS.listarTodasClientesRequest inValue = new InventStar.ClientesWS.listarTodasClientesRequest();
            InventStar.ClientesWS.listarTodasClientesResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).listarTodasClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasClientesResponse> InventStar.ClientesWS.ClientesWS.listarTodasClientesAsync(InventStar.ClientesWS.listarTodasClientesRequest request) {
            return base.Channel.listarTodasClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasClientesResponse> listarTodasClientesAsync() {
            InventStar.ClientesWS.listarTodasClientesRequest inValue = new InventStar.ClientesWS.listarTodasClientesRequest();
            return ((InventStar.ClientesWS.ClientesWS)(this)).listarTodasClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.listarTodasTarjetasResponse InventStar.ClientesWS.ClientesWS.listarTodasTarjetas(InventStar.ClientesWS.listarTodasTarjetasRequest request) {
            return base.Channel.listarTodasTarjetas(request);
        }
        
        public InventStar.ClientesWS.tarjetaInventstar[] listarTodasTarjetas() {
            InventStar.ClientesWS.listarTodasTarjetasRequest inValue = new InventStar.ClientesWS.listarTodasTarjetasRequest();
            InventStar.ClientesWS.listarTodasTarjetasResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).listarTodasTarjetas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasTarjetasResponse> InventStar.ClientesWS.ClientesWS.listarTodasTarjetasAsync(InventStar.ClientesWS.listarTodasTarjetasRequest request) {
            return base.Channel.listarTodasTarjetasAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasTarjetasResponse> listarTodasTarjetasAsync() {
            InventStar.ClientesWS.listarTodasTarjetasRequest inValue = new InventStar.ClientesWS.listarTodasTarjetasRequest();
            return ((InventStar.ClientesWS.ClientesWS)(this)).listarTodasTarjetasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.listarTodasPromocionesResponse InventStar.ClientesWS.ClientesWS.listarTodasPromociones(InventStar.ClientesWS.listarTodasPromocionesRequest request) {
            return base.Channel.listarTodasPromociones(request);
        }
        
        public InventStar.ClientesWS.promocionPersonalizada[] listarTodasPromociones(int arg0) {
            InventStar.ClientesWS.listarTodasPromocionesRequest inValue = new InventStar.ClientesWS.listarTodasPromocionesRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.listarTodasPromocionesResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).listarTodasPromociones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasPromocionesResponse> InventStar.ClientesWS.ClientesWS.listarTodasPromocionesAsync(InventStar.ClientesWS.listarTodasPromocionesRequest request) {
            return base.Channel.listarTodasPromocionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.listarTodasPromocionesResponse> listarTodasPromocionesAsync(int arg0) {
            InventStar.ClientesWS.listarTodasPromocionesRequest inValue = new InventStar.ClientesWS.listarTodasPromocionesRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).listarTodasPromocionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.eliminarPromocionResponse InventStar.ClientesWS.ClientesWS.eliminarPromocion(InventStar.ClientesWS.eliminarPromocionRequest request) {
            return base.Channel.eliminarPromocion(request);
        }
        
        public int eliminarPromocion(int arg0) {
            InventStar.ClientesWS.eliminarPromocionRequest inValue = new InventStar.ClientesWS.eliminarPromocionRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.eliminarPromocionResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).eliminarPromocion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarPromocionResponse> InventStar.ClientesWS.ClientesWS.eliminarPromocionAsync(InventStar.ClientesWS.eliminarPromocionRequest request) {
            return base.Channel.eliminarPromocionAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarPromocionResponse> eliminarPromocionAsync(int arg0) {
            InventStar.ClientesWS.eliminarPromocionRequest inValue = new InventStar.ClientesWS.eliminarPromocionRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).eliminarPromocionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.eliminarResponse InventStar.ClientesWS.ClientesWS.eliminar(InventStar.ClientesWS.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(int arg0) {
            InventStar.ClientesWS.eliminarRequest inValue = new InventStar.ClientesWS.eliminarRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.eliminarResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarResponse> InventStar.ClientesWS.ClientesWS.eliminarAsync(InventStar.ClientesWS.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarResponse> eliminarAsync(int arg0) {
            InventStar.ClientesWS.eliminarRequest inValue = new InventStar.ClientesWS.eliminarRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.insertarClienteResponse InventStar.ClientesWS.ClientesWS.insertarCliente(InventStar.ClientesWS.insertarClienteRequest request) {
            return base.Channel.insertarCliente(request);
        }
        
        public int insertarCliente(InventStar.ClientesWS.cliente arg0) {
            InventStar.ClientesWS.insertarClienteRequest inValue = new InventStar.ClientesWS.insertarClienteRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.insertarClienteResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).insertarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.insertarClienteResponse> InventStar.ClientesWS.ClientesWS.insertarClienteAsync(InventStar.ClientesWS.insertarClienteRequest request) {
            return base.Channel.insertarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.insertarClienteResponse> insertarClienteAsync(InventStar.ClientesWS.cliente arg0) {
            InventStar.ClientesWS.insertarClienteRequest inValue = new InventStar.ClientesWS.insertarClienteRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).insertarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.eliminarTarjetaResponse InventStar.ClientesWS.ClientesWS.eliminarTarjeta(InventStar.ClientesWS.eliminarTarjetaRequest request) {
            return base.Channel.eliminarTarjeta(request);
        }
        
        public int eliminarTarjeta(int arg0) {
            InventStar.ClientesWS.eliminarTarjetaRequest inValue = new InventStar.ClientesWS.eliminarTarjetaRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.eliminarTarjetaResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).eliminarTarjeta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarTarjetaResponse> InventStar.ClientesWS.ClientesWS.eliminarTarjetaAsync(InventStar.ClientesWS.eliminarTarjetaRequest request) {
            return base.Channel.eliminarTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.eliminarTarjetaResponse> eliminarTarjetaAsync(int arg0) {
            InventStar.ClientesWS.eliminarTarjetaRequest inValue = new InventStar.ClientesWS.eliminarTarjetaRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).eliminarTarjetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.modificarClienteResponse InventStar.ClientesWS.ClientesWS.modificarCliente(InventStar.ClientesWS.modificarClienteRequest request) {
            return base.Channel.modificarCliente(request);
        }
        
        public int modificarCliente(InventStar.ClientesWS.cliente arg0) {
            InventStar.ClientesWS.modificarClienteRequest inValue = new InventStar.ClientesWS.modificarClienteRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.modificarClienteResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).modificarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.modificarClienteResponse> InventStar.ClientesWS.ClientesWS.modificarClienteAsync(InventStar.ClientesWS.modificarClienteRequest request) {
            return base.Channel.modificarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.modificarClienteResponse> modificarClienteAsync(InventStar.ClientesWS.cliente arg0) {
            InventStar.ClientesWS.modificarClienteRequest inValue = new InventStar.ClientesWS.modificarClienteRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).modificarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.insertarTarjetaResponse InventStar.ClientesWS.ClientesWS.insertarTarjeta(InventStar.ClientesWS.insertarTarjetaRequest request) {
            return base.Channel.insertarTarjeta(request);
        }
        
        public int insertarTarjeta(InventStar.ClientesWS.tarjetaInventstar arg0) {
            InventStar.ClientesWS.insertarTarjetaRequest inValue = new InventStar.ClientesWS.insertarTarjetaRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.insertarTarjetaResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).insertarTarjeta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.insertarTarjetaResponse> InventStar.ClientesWS.ClientesWS.insertarTarjetaAsync(InventStar.ClientesWS.insertarTarjetaRequest request) {
            return base.Channel.insertarTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.insertarTarjetaResponse> insertarTarjetaAsync(InventStar.ClientesWS.tarjetaInventstar arg0) {
            InventStar.ClientesWS.insertarTarjetaRequest inValue = new InventStar.ClientesWS.insertarTarjetaRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).insertarTarjetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InventStar.ClientesWS.modificarTarjetaResponse InventStar.ClientesWS.ClientesWS.modificarTarjeta(InventStar.ClientesWS.modificarTarjetaRequest request) {
            return base.Channel.modificarTarjeta(request);
        }
        
        public int modificarTarjeta(InventStar.ClientesWS.tarjetaInventstar arg0) {
            InventStar.ClientesWS.modificarTarjetaRequest inValue = new InventStar.ClientesWS.modificarTarjetaRequest();
            inValue.arg0 = arg0;
            InventStar.ClientesWS.modificarTarjetaResponse retVal = ((InventStar.ClientesWS.ClientesWS)(this)).modificarTarjeta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InventStar.ClientesWS.modificarTarjetaResponse> InventStar.ClientesWS.ClientesWS.modificarTarjetaAsync(InventStar.ClientesWS.modificarTarjetaRequest request) {
            return base.Channel.modificarTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InventStar.ClientesWS.modificarTarjetaResponse> modificarTarjetaAsync(InventStar.ClientesWS.tarjetaInventstar arg0) {
            InventStar.ClientesWS.modificarTarjetaRequest inValue = new InventStar.ClientesWS.modificarTarjetaRequest();
            inValue.arg0 = arg0;
            return ((InventStar.ClientesWS.ClientesWS)(this)).modificarTarjetaAsync(inValue);
        }
    }
}
